apiVersion: ocs.openshift.io/v1alpha1
kind: StorageClient
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage-client
spec:
  storageProviderEndpoint: PLACEHOLDER1
  onboardingTicket: >-
    PLACEHOLDER2
